---
- name: demon reloading 
  systemd:
    daemon_reload: yes

- name: enabling tomcat service
  systemd: 
    name: tomcat
    state: started
- name: copy config file into  tomcat.service file
  file:
     src: templates/myconf.j2
     dest: /etc/systemd/system/tomcat.service